# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- main

variables:
  exercise: $[ variables['Build.SourceVersionMessage'] ]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd exercise-1
    npm install
    npm run test-report
  displayName: 'Testing Exercise 1'
  condition: eq(variables.exercise, '1')

- script: |
    cd exercise-2
    npm install
    npm run test-report
  displayName: 'Testing Exercise 2'
  condition: eq(exercise, '2')

- script: |
    cd exercise-3
    npm install
    npm run test-report
  displayName: 'Testing Exercise 3'
  condition: eq(exercise, '3')

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: false
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'