# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- main

variables:
  exercise: $[ variables['Build.SourceVersionMessage'] ]
  exercisePR: $[ variables['System.PullRequest.SourceBranch'] ]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd exercise-1
    npm install
    npm run test-report
  displayName: 'Testing Exercise 1'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex1'),contains(variables.exercisePR, 'ex1'))

- script: |
    cd exercise-2
    npm install
    npm run test-report
  displayName: 'Testing Exercise 2'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex2'),contains(variables.exercisePR, 'ex2'))

- script: |
    cd exercise-3
    npm install
    npm run test-report
  displayName: 'Testing Exercise 3'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex3'),contains(variables.exercisePR, 'ex3'))

- script: |
    cd exercise-4
    npm install
    npm run test-report
  displayName: 'Testing Exercise 4'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex4'),contains(variables.exercisePR, 'ex4'))

- script: |
    cd exercise-5
    npm install
    npm run test-report
  displayName: 'Testing Exercise 5'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex5'),contains(variables.exercisePR, 'ex5'))

- script: |
    cd exercise-6
    npm install
    npm run test-report
  displayName: 'Testing Exercise 6'
  continueOnError: true
  condition: or(contains(variables.exercise, 'ex6'),contains(variables.exercisePR, 'ex6'))

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
