# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- main

variables:
  exercise: $[ variables['Build.SourceVersionMessage'] ]
  exercisePR: $[ variables['System.PullRequest.SourceBranch'] ]

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd exercise-1
    npm install
    npm run test-report
  displayName: 'Testing Exercise 1'
  continueOnError: true
  condition: or(eq(variables.exercise, '1'),eq(variables.exercisePR, '1'))

- script: |
    cd exercise-2
    npm install
    npm run test-report
  displayName: 'Testing Exercise 2'
  continueOnError: true
  condition: or(eq(variables.exercise, '2'),eq(variables.exercisePR, '2'))

- script: |
    cd exercise-3
    npm install
    npm run test-report
  displayName: 'Testing Exercise 3'
  continueOnError: true
  condition: or(eq(variables.exercise, '3'),eq(variables.exercisePR, '3'))

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'